### ISSUE TITLE
Basic housekeepings

### ISSUE THREAD

**Issue by simnalamburt** [LastOne817/graduate#2]
I'm currently performing basic houskeepings to this project at [simnalamburt/graduate](https://github.com/simnalamburt/graduate)

#### TODOs
- [x] Specify code license &rarr; MIT
- Document basic instructions
  - [x] Prerequisites &rarr; #3 
  - [x] How to run the server &rarr; #3 
- Housekeeping
  - [x] `requirements.txt` &rarr; #3 
  - [x] ~~Adopt editorconfig~~ &rarr; don't
  - [x] Check source codes encoding, etc &rarr; #3 
  - [x] Remove log files &rarr; #4
  - [x] Update `.gitignore` rules  &rarr; #4
- DB
  - [ ] Mention it on prerequisites
  - [ ] Document it how to setup
  - [ ] Use sqlite3 in development mode, and switch to MySQL or others only in production mode
- CI
  - [ ] flake8
  - [ ] Unit testing
- Issues which is not related with the codes
  - [ ] Make my own working server for development purpose
  - [ ] Apply let's encrypt

**Comment by simnalamburt** [comment]
@LastOne817 I'm planning to change the code to use [SQLite] in development mode, making this application to use MySQL only in production mode. In this way, it'll be both much easier to setup development environment (since we don't need to setup MySQL server) and testable with CI.

How do you think? Will you merge that change if I propose that PR later?

[SQLite]: https://sqlite.org/

**Comment by dj-shin** [comment]
@simnalamburt I don't think it will be a problem, since the only model currently exists is `Course` and it's a rather basic one.
